# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79debab6241f59998ae51707282527fd687b4e7ba3da865aa713cbfa43857490f96bf687ced4ec1ea32339d82161858cb1da0163e38bec8516677be16fe241b8

test:
  secret_key_base: da900b1b61fafff5f35221c199bd5091b438659e994f3631cb1505f51f706ceb9cb47ce69c8ff55e6cd0e56c052bfe86c96413912de417a399682a09a3e08a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
